### ISSUE TITLE
config error make another exception occur

### ISSUE THREAD

**Issue by liuminhaw** [liuminhaw/tickets#2]
#### Description
- when executing `booking.py daan-sport`
- config file option format error: section wrong format: might
- During handling of the above exception, another exception occurred

#### Error Message
```
Traceback (most recent call last):
  File "/home/haw/github.com/liuminhaw/tickets/general_pkg/search.py", line 67, in _config_test
    ret_val = func(*args)
  File "/home/haw/github.com/liuminhaw/tickets/module_pkg/driver.py", line 92, in read_conf
    self.booking_section = config.section(section)
  File "/home/haw/github.com/liuminhaw/tickets/module_pkg/conf_mod.py", line 187, in section
    self._validate('morning|evening|night', self.SECTION, _section)
  File "/home/haw/github.com/liuminhaw/tickets/module_pkg/conf_mod.py", line 228, in _validate
    raise OptionFormatError(key, value)
module_pkg.conf_mod.OptionFormatError: ('section', 'might')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "booking.py", line 194, in <module>
    main()
  File "booking.py", line 66, in main
    elected = search.search(config, data_section)
  File "/home/haw/github.com/liuminhaw/tickets/general_pkg/search.py", line 27, in search
    _config_test(browser.read_conf, config, section, "action='search'")
  File "/home/haw/github.com/liuminhaw/tickets/general_pkg/search.py", line 83, in _config_test
    sys.exit(14)
NameError: name 'sys' is not defined
```

**Comment by liuminhaw** [comment]
Import `sys` to `search` package
